### ISSUE TITLE
Running ogmail does nothing.

### ISSUE THREAD

**Issue by CameronBanga** [max-mapper/ogmail#1]
Set up my googleauth, have token saved in ~/.config/googleauth.json, but having no luck when I run ogmail. No error output, no prompts, anything. See about 5-10 seconds of processing, then returned to command prompt. Any thoughts?

**Comment by CameronBanga** [comment]
As a note, looks like API hits are coming in successfully in my Google Dev console, so don't think it's an authentication issue?

**Comment by max-mapper** [comment]
oh I was hacking on it earlier on a train (was offline at the time) and may
have accidentally broke it. I'll fix it tomorrow. sorry!

**Comment by CameronBanga** [comment]
No worries, thanks man. Excited to try it out.

**Comment by clkao** [comment]
it seems to be piping to inbox() which returns the colorized string but not printing it anymore.
